/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import Obj.Kardex;
import Obj.Empleado;

/**
 *
 * @author Dildo__Queen
 */
public class App extends javax.swing.JFrame {

    private Kardex krdx = null;
    private Empleado venddr = null;
    public RealizarVenta rVenta = null;
    private Productos prodcts = null;
    private Clientes clints = null;
    public Ventas vents = null;

    /**
     *
     * @param kardex
     * @param vendedor
     * @throws Exception
     */
    public App(Kardex kardex, Empleado vendedor) throws Exception {
        this.krdx = kardex;
        this.venddr = vendedor;
        this.rVenta = new RealizarVenta(this.krdx, this.venddr, this);
        this.prodcts = new Productos(this.krdx, this.venddr, this);
        this.clints = new Clientes(this.krdx, this.venddr);
        this.vents = new Ventas(this.krdx, this.venddr);
        initComponents();
        this.setLocationRelativeTo(null);
        tbpPrincipal.add(rVenta);
        tbpPrincipal.setTitleAt(0, "Realizar venta");
        tbpPrincipal.add(prodcts);
        tbpPrincipal.setTitleAt(1, "Productos");
        tbpPrincipal.add(clints);
        tbpPrincipal.setTitleAt(2, "Clientes");
        tbpPrincipal.add(vents);
        tbpPrincipal.setTitleAt(3, "Ventas");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbpPrincipal = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(krdx.getNombre());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tbpPrincipal;
    // End of variables declaration//GEN-END:variables
}
