/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import Obj.Cliente;
import Obj.Kardex;
import Obj.Vendedor;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author Dildo__Queen
 */
public class Clientes extends javax.swing.JPanel {

    private Kardex krdx = null;
    private Vendedor venddr = null;

    /**
     * Creates new form Clientes
     */
    public Clientes(Kardex kardex, Vendedor vendedor) {
        this.krdx = kardex;
        this.venddr = vendedor;
        initComponents();
        init();
    }

    public void init() {
        tblClientes.setModel(new AbstractTableModel() {
            String[] nmColumnas = {"Identificacion", "Cliente"};

            @Override
            public String getColumnName(int column) {
                return nmColumnas[column];
            }

            @Override
            public int getRowCount() {
                if (krdx.getClientes().isEmpty()) {
                    return 0;
                }
                return krdx.getClientes().size();
            }

            @Override
            public int getColumnCount() {
                return nmColumnas.length;
            }

            @Override
            public Object getValueAt(int rowIndex, int columnIndex) {
                Cliente ctmp = krdx.getClientes().get(rowIndex);
                if (columnIndex == 0) {
                    return ctmp.getIdentificacion();
                } else if (columnIndex == 1) {
                    return ctmp.getNombre();
                }
                return "";
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlNuevoCliente = new javax.swing.JPanel();
        lblNuevoIdentificacion = new javax.swing.JLabel();
        lblNuevoNombre = new javax.swing.JLabel();
        txtfNuevoIdentificacion = new javax.swing.JTextField();
        txtfNuevoNombre = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        scpClientes = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(472, 600));

        pnlNuevoCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Nuevo cliente"));

        lblNuevoIdentificacion.setText("Identificacion:");

        lblNuevoNombre.setText("Nombre:");

        txtfNuevoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EvtNuevoCliente(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EvtNuevoCliente(evt);
            }
        });

        javax.swing.GroupLayout pnlNuevoClienteLayout = new javax.swing.GroupLayout(pnlNuevoCliente);
        pnlNuevoCliente.setLayout(pnlNuevoClienteLayout);
        pnlNuevoClienteLayout.setHorizontalGroup(
            pnlNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNuevoClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNuevoClienteLayout.createSequentialGroup()
                        .addGroup(pnlNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNuevoIdentificacion)
                            .addComponent(lblNuevoNombre))
                        .addGap(18, 18, 18)
                        .addGroup(pnlNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtfNuevoIdentificacion)
                            .addComponent(txtfNuevoNombre)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNuevoClienteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGuardar)))
                .addContainerGap())
        );
        pnlNuevoClienteLayout.setVerticalGroup(
            pnlNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNuevoClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNuevoIdentificacion)
                    .addComponent(txtfNuevoIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNuevoNombre)
                    .addComponent(txtfNuevoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnGuardar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scpClientes.setViewportView(tblClientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlNuevoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scpClientes))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scpClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void EvtNuevoCliente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EvtNuevoCliente
        try {
            Cliente ctmp = new Cliente(txtfNuevoIdentificacion.getText(), txtfNuevoNombre.getText());
            this.krdx.add(ctmp);
            txtfNuevoIdentificacion.setText("");
            txtfNuevoNombre.setText("");
        } catch (Exception ex) {
            Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(pnlNuevoCliente, "Warning\n\n" + ex.getMessage(), krdx.getNombre() + " Warning", JOptionPane.WARNING_MESSAGE);
        }
        tblClientes.updateUI();
    }//GEN-LAST:event_EvtNuevoCliente


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel lblNuevoIdentificacion;
    private javax.swing.JLabel lblNuevoNombre;
    private javax.swing.JPanel pnlNuevoCliente;
    private javax.swing.JScrollPane scpClientes;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtfNuevoIdentificacion;
    private javax.swing.JTextField txtfNuevoNombre;
    // End of variables declaration//GEN-END:variables
}
