/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import Obj.Kardex;
import Obj.Producto;
import Obj.Empleado;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author Dildo__Queen
 */
public class Productos extends javax.swing.JPanel {

    private Kardex krdx = null;
    private Empleado venddr = null;
    private App appRun = null;

    /**
     *
     * @param kardex
     * @param vendedor
     */
    public Productos(Kardex kardex, Empleado vendedor, App app) {
        this.krdx = kardex;
        this.venddr = vendedor;
        this.appRun = app;
        initComponents();
        init();
    }

    public void init() {
        tblTodosLosProductos.setModel(new AbstractTableModel() {
            String[] nmColumnas = {"Codigo", "Nombre", "Total", "Descripcion"};

            @Override
            public String getColumnName(int column) {
                return nmColumnas[column];
            }

            @Override
            public int getRowCount() {
                if (krdx.getProductos().isEmpty()) {
                    return 0;
                }
                return krdx.getProductos().size();
            }

            @Override
            public int getColumnCount() {
                return nmColumnas.length;
            }

            @Override
            public Object getValueAt(int rowIndex, int columnIndex) {
                Producto ptmp = krdx.getProductos().get(rowIndex);
                if (columnIndex == 0) {
                    return ptmp.getCodigo();
                } else if (columnIndex == 1) {
                    return ptmp.getNombre();
                } else if (columnIndex == 2) {
                    return ptmp.getCosto();
                } else if (columnIndex == 3) {
                    return ptmp.getDescripcion();
                }
                return "";
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlProductoNuevo = new javax.swing.JPanel();
        lblNuevoCodigo = new javax.swing.JLabel();
        lblNuevoNombre = new javax.swing.JLabel();
        lblNuevoDescripcion = new javax.swing.JLabel();
        lblNuevoCosto = new javax.swing.JLabel();
        txtfNuevoCodigo = new javax.swing.JTextField();
        txtfNuevoNombre = new javax.swing.JTextField();
        txtfNuevoDescripcion = new javax.swing.JTextField();
        txtfNuevoCosto = new javax.swing.JTextField();
        btnNuevoProducto = new javax.swing.JButton();
        pnlProductos = new javax.swing.JPanel();
        scpTodosLosProductos = new javax.swing.JScrollPane();
        tblTodosLosProductos = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(472, 600));

        pnlProductoNuevo.setBorder(javax.swing.BorderFactory.createTitledBorder("Nuevo producto"));

        lblNuevoCodigo.setText("Codigo:");

        lblNuevoNombre.setText("Nombre:");

        lblNuevoDescripcion.setText("Descripcion:");

        lblNuevoCosto.setText("Costo:");

        txtfNuevoCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EvtAddProducto(evt);
            }
        });

        btnNuevoProducto.setText("Guardar");
        btnNuevoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EvtAddProducto(evt);
            }
        });

        javax.swing.GroupLayout pnlProductoNuevoLayout = new javax.swing.GroupLayout(pnlProductoNuevo);
        pnlProductoNuevo.setLayout(pnlProductoNuevoLayout);
        pnlProductoNuevoLayout.setHorizontalGroup(
            pnlProductoNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductoNuevoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProductoNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProductoNuevoLayout.createSequentialGroup()
                        .addComponent(lblNuevoCodigo)
                        .addGap(18, 18, 18)
                        .addComponent(txtfNuevoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblNuevoNombre)
                        .addGap(18, 18, 18)
                        .addComponent(txtfNuevoNombre))
                    .addGroup(pnlProductoNuevoLayout.createSequentialGroup()
                        .addComponent(lblNuevoDescripcion)
                        .addGap(18, 18, 18)
                        .addComponent(txtfNuevoDescripcion))
                    .addGroup(pnlProductoNuevoLayout.createSequentialGroup()
                        .addComponent(lblNuevoCosto)
                        .addGap(18, 18, 18)
                        .addComponent(txtfNuevoCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnNuevoProducto)
                        .addGap(0, 141, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlProductoNuevoLayout.setVerticalGroup(
            pnlProductoNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductoNuevoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProductoNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNuevoCodigo)
                    .addComponent(txtfNuevoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNuevoNombre)
                    .addComponent(txtfNuevoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlProductoNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNuevoDescripcion)
                    .addComponent(txtfNuevoDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlProductoNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNuevoCosto)
                    .addComponent(btnNuevoProducto)
                    .addComponent(txtfNuevoCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlProductos.setBorder(javax.swing.BorderFactory.createTitledBorder("Todos los productos"));

        tblTodosLosProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scpTodosLosProductos.setViewportView(tblTodosLosProductos);

        javax.swing.GroupLayout pnlProductosLayout = new javax.swing.GroupLayout(pnlProductos);
        pnlProductos.setLayout(pnlProductosLayout);
        pnlProductosLayout.setHorizontalGroup(
            pnlProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scpTodosLosProductos, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlProductosLayout.setVerticalGroup(
            pnlProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scpTodosLosProductos, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlProductoNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlProductoNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void EvtAddProducto(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EvtAddProducto
        try {
            String codigo = txtfNuevoCodigo.getText().toUpperCase();
            String nombre = txtfNuevoNombre.getText();
            String descripcion = txtfNuevoDescripcion.getText();
            String costo = txtfNuevoCosto.getText().trim();
            Producto ptmp = new Producto(codigo, nombre, descripcion, Float.parseFloat(costo));
            krdx.add(ptmp);
            txtfNuevoCodigo.setText("");
            txtfNuevoNombre.setText("");
            txtfNuevoDescripcion.setText("");
            txtfNuevoCosto.setText("");
            tblTodosLosProductos.updateUI();
            appRun.rVenta.cmbProducto.addItem(ptmp);
        } catch (Exception ex) {
            Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(btnNuevoProducto, "La operacion no se pudo completar\n\n" + ex.getMessage(), krdx.getNombre() + " Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_EvtAddProducto


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevoProducto;
    private javax.swing.JLabel lblNuevoCodigo;
    private javax.swing.JLabel lblNuevoCosto;
    private javax.swing.JLabel lblNuevoDescripcion;
    private javax.swing.JLabel lblNuevoNombre;
    private javax.swing.JPanel pnlProductoNuevo;
    private javax.swing.JPanel pnlProductos;
    private javax.swing.JScrollPane scpTodosLosProductos;
    private javax.swing.JTable tblTodosLosProductos;
    private javax.swing.JTextField txtfNuevoCodigo;
    private javax.swing.JTextField txtfNuevoCosto;
    private javax.swing.JTextField txtfNuevoDescripcion;
    private javax.swing.JTextField txtfNuevoNombre;
    // End of variables declaration//GEN-END:variables
}
