/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import Obj.Empleado;
import Obj.Kardex;
import Obj.Producto;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author Dildo__Queen
 */
public class Productos extends javax.swing.JPanel {

    private Kardex krdx = null;
    private Empleado empld = null;

    /**
     *
     * @param kardex
     * @param empleado
     */
    public Productos(Kardex kardex, Empleado empleado) {
        this.krdx = kardex;
        this.empld = empleado;
        initComponents();
        init();
    }

    public void init() {
        this.tblTodos.setModel(new AbstractTableModel() {
            String[] nmColumnas = {"Codigo", "Nombre", "Costo", "Descripcion"};

            @Override
            public String getColumnName(int column) {
                return nmColumnas[column];
            }

            @Override
            public int getRowCount() {
                try {
                    if (!krdx.getProductos().isEmpty()) {
                        return krdx.getProductos().size();
                    }
                } catch (Exception ex) {
                    Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
                }
                return 0;
            }

            @Override
            public int getColumnCount() {
                return nmColumnas.length;
            }

            @Override
            public Object getValueAt(int rowIndex, int columnIndex) {
                try {
                    Producto ptmp = (Producto) krdx.getProductos().get(rowIndex);
                    if (columnIndex == 0) {
                        return ptmp.getCodigo();
                    } else if (columnIndex == 1) {
                        return ptmp.getNombre();
                    } else if (columnIndex == 2) {
                        return ptmp.getCosto();
                    } else if (columnIndex == 3) {
                        return ptmp.getDescripcion();
                    }
                } catch (Exception e) {
                    Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, e);
                }
                return "";
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlProductoNuevo = new javax.swing.JPanel();
        lblProductoId = new javax.swing.JLabel();
        lblProductoNombre = new javax.swing.JLabel();
        lblProductoDescripcion = new javax.swing.JLabel();
        lblProductoCosto = new javax.swing.JLabel();
        txtfProductoId = new javax.swing.JTextField();
        txtfProductoNombre = new javax.swing.JTextField();
        txtfProductoDescripcion = new javax.swing.JTextField();
        txtfProductoCosto = new javax.swing.JTextField();
        btnProductoAceptar = new javax.swing.JButton();
        pnlTodosLosProductos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTodos = new javax.swing.JTable();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(472, 600));

        pnlProductoNuevo.setBorder(javax.swing.BorderFactory.createTitledBorder("Nuevo producto"));

        lblProductoId.setText("Id:");

        lblProductoNombre.setText("Nombre:");

        lblProductoDescripcion.setText("Descripcion:");

        lblProductoCosto.setText("Costo:");

        btnProductoAceptar.setText("Aceptar");

        javax.swing.GroupLayout pnlProductoNuevoLayout = new javax.swing.GroupLayout(pnlProductoNuevo);
        pnlProductoNuevo.setLayout(pnlProductoNuevoLayout);
        pnlProductoNuevoLayout.setHorizontalGroup(
            pnlProductoNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductoNuevoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProductoNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblProductoCosto)
                    .addComponent(lblProductoDescripcion)
                    .addComponent(lblProductoNombre)
                    .addComponent(lblProductoId))
                .addGap(18, 18, 18)
                .addGroup(pnlProductoNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtfProductoDescripcion)
                    .addComponent(txtfProductoNombre)
                    .addGroup(pnlProductoNuevoLayout.createSequentialGroup()
                        .addGroup(pnlProductoNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtfProductoId, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlProductoNuevoLayout.createSequentialGroup()
                                .addComponent(txtfProductoCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnProductoAceptar)))
                        .addGap(0, 135, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlProductoNuevoLayout.setVerticalGroup(
            pnlProductoNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductoNuevoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProductoNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProductoId)
                    .addComponent(txtfProductoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlProductoNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProductoNombre)
                    .addComponent(txtfProductoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlProductoNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProductoDescripcion)
                    .addComponent(txtfProductoDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlProductoNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProductoCosto)
                    .addComponent(txtfProductoCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProductoAceptar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlTodosLosProductos.setBorder(javax.swing.BorderFactory.createTitledBorder("Todos los productos"));

        tblTodos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTodos);

        javax.swing.GroupLayout pnlTodosLosProductosLayout = new javax.swing.GroupLayout(pnlTodosLosProductos);
        pnlTodosLosProductos.setLayout(pnlTodosLosProductosLayout);
        pnlTodosLosProductosLayout.setHorizontalGroup(
            pnlTodosLosProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTodosLosProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTodosLosProductosLayout.setVerticalGroup(
            pnlTodosLosProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTodosLosProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlTodosLosProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlProductoNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlProductoNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlTodosLosProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProductoAceptar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblProductoCosto;
    private javax.swing.JLabel lblProductoDescripcion;
    private javax.swing.JLabel lblProductoId;
    private javax.swing.JLabel lblProductoNombre;
    private javax.swing.JPanel pnlProductoNuevo;
    private javax.swing.JPanel pnlTodosLosProductos;
    private javax.swing.JTable tblTodos;
    private javax.swing.JTextField txtfProductoCosto;
    private javax.swing.JTextField txtfProductoDescripcion;
    private javax.swing.JTextField txtfProductoId;
    private javax.swing.JTextField txtfProductoNombre;
    // End of variables declaration//GEN-END:variables
}
