/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import Obj.Kardex;
import Obj.Venta;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author Dildo__Queen
 */
public class Ventas extends javax.swing.JPanel {

    private Kardex krdx = null;

    /**
     *
     * @param kardex
     */
    public Ventas(Kardex kardex) {
        this.krdx = kardex;
        initComponents();
        init();
    }

    public void init() {
        this.tblTodas.setModel(new AbstractTableModel() {
            String[] nmColumnas = {"Id", "Fecha", "Cliente", "Total"};

            @Override
            public String getColumnName(int column) {
                return nmColumnas[column];
            }

            @Override
            public int getRowCount() {
                try {
                    if (!krdx.getVentas().isEmpty()) {
                        return krdx.getVentas().size();
                    }
                } catch (Exception e) {
                    Logger.getLogger(Ventas.class.getName()).log(Level.SEVERE, null, e);
                }
                return 0;
            }

            @Override
            public int getColumnCount() {
                return nmColumnas.length;
            }

            @Override
            public Object getValueAt(int rowIndex, int columnIndex) {
                try {
                    Venta vtpm = (Venta) krdx.getVentas().get(rowIndex);
                    SimpleDateFormat f = new SimpleDateFormat("dd/MM/yyyy");
                    if (columnIndex == 0) {
                        return vtpm.getId();
                    } else if (columnIndex == 1) {
                        return f.format(vtpm.getFecha());
                    } else if (columnIndex == 2) {
                        return vtpm.getCliente().toString();
                    } else if (columnIndex == 3) {
                        return vtpm.getSubtotal();
                    }
                } catch (Exception e) {
                    Logger.getLogger(Ventas.class.getName()).log(Level.SEVERE, null, e);
                }
                return "";
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblTodas = new javax.swing.JTable();
        lblTodas = new javax.swing.JLabel();

        tblTodas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTodas);

        lblTodas.setText("Todas las ventas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTodas)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTodas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTodas;
    private javax.swing.JTable tblTodas;
    // End of variables declaration//GEN-END:variables
}
